@startuml
entity Kostenpunkt
{
    * **ID <<PK>>**
    * Bezeichnung
    * Datum
    * Betrag
    * **KostenID <<FK>>**
}

entity Benutzer
{
    * **ID <<PK>>**
    * Nachname
    * Vorname
}

entity Login
{
    * **ID <<PK>>**
    * E-Mail-Adresse
    * Benutzername
    * Salt
    * Passwort
    * **BenutzerID <<FK>>**
}

entity Kosten
{
    * **ID <<PK>>**
    * Bezeichnung
}

entity Einnahmequelle
{
    * **ID <<PK>>**
    * Bezeichnung
    * Turnus
    * Betrag
    * **BenutzerID <<FK>>**
}

Kosten ||--o{ Kostenpunkt
Kostenpunkt }o--|| Benutzer
Benutzer ||--o{ Einnahmequelle
Benutzer ||--|| Login
@enduml
